### ISSUE TITLE
Provide priority fee option when sending asset

### ISSUE THREAD

**Issue by wanglongfei88** [NeoNextClub/neoline#4]
When user use NEOLine  to send assets like NEO or GAS, user may choose to pay extra fee to make their tx be process earlier. 

So this optional function is necessary, can you please add it ?

**Comment by hactrox** [comment]
A 'fee' option is added both to user interface and dapi arguments. 
It will be available from next release(0.9.4).

**Comment by denissuslov** [comment]
Please add suggested Priority Fee amount 0.0011 as in other wallets (as on image attached), otherwise is confusing what amount to add.
<img width="206" alt="priority fee" src="https://user-images.githubusercontent.com/43337546/56342105-a41aba00-61e9-11e9-94ae-ad19cca44c5a.png">

Also please change words Network Fee to Priority Fee （优先处理费） for clarity.

**Comment by denissuslov** [comment]
Also please add Priority Fee function to sending NEP5 tokens

**Comment by hactrox** [comment]
@denissuslov This missing feature was included into our new release, check it out :)
